// Code generated by MCHP Chatbot

#include "botones.h"
#include "config.h"
#include "eeprom.h"
#include "I2C_LCD.h"

// Variables privadas de anti-rebote (no necesitan ser globales)
static uint8_t rb0_prev = 1, rb1_prev = 1, rb2_prev = 1;
static uint16_t rb0_hold_count = 0;
static uint8_t  rb0_hold_fired = 0;
static uint8_t  rb0_debounce   = 0;
static uint8_t  rb1_debounce   = 0;
static uint8_t  rb2_debounce   = 0;

void leer_botones(void) {
    uint8_t rb0 = (BTN_MODE == 0);
    uint8_t rb1 = (BTN_UP == 0);
    uint8_t rb2 = (BTN_DOWN == 0);

    uint8_t rb0_was = rb0_prev;
    uint8_t rb1_was = rb1_prev;
    uint8_t rb2_was = rb2_prev;

    // Debounce control
    if (rb0 != rb0_prev) rb0_debounce = 0;
    if (rb1 != rb1_prev) rb1_debounce = 0;
    if (rb2 != rb2_prev) rb2_debounce = 0;
    if (rb0_debounce < 5) rb0_debounce++;
    if (rb1_debounce < 5) rb1_debounce++;
    if (rb2_debounce < 5) rb2_debounce++;
    rb0_prev = rb0;
    rb1_prev = rb1;
    rb2_prev = rb2;

    // MODE button (RB0)
    if (rb0 && rb0_debounce == 5) {
            rb0_hold_count++;
        if (!rb0_hold_fired && rb0_hold_count >= 2000) {
                rb0_hold_fired = 1;
                if (modo_actual != MODO_CONFIG) {
                    modo_anterior = modo_actual;
                modo_actual = MODO_CONFIG;
                campo_edit = EDIT_VON;
                    LCD_Clear();
                } else {
                    guardar_umbrales_EEPROM();
                    modo_actual = modo_anterior;
                    LCD_Clear();
                }
            }
        }
    if (!rb0 && rb0_was && rb0_debounce == 5) {
        // Short press (if not a long press)
        if (!rb0_hold_fired) {
            if (modo_actual == MODO_CONFIG) {
                campo_edit = (campo_edit == EDIT_VON) ? EDIT_VOFF : EDIT_VON;
            } else if (modo_actual == MODO_AUTO) {
                if (vista_actual == VISTA_NORMAL) vista_actual = VISTA_MAX;
                else if (vista_actual == VISTA_MAX) vista_actual = VISTA_MIN;
                else vista_actual = VISTA_NORMAL;
                LCD_Clear();
            } else if (modo_actual == MODO_MANUAL) {
                modo_actual = MODO_AUTO;
                vista_actual = VISTA_NORMAL;
        LCD_Clear();
    }
        }
        rb0_hold_count = 0;
        rb0_hold_fired = 0;
    }

    // RB1 + RB2 simultaneous in MODO_AUTO
    if (modo_actual == MODO_AUTO && rb1 && rb2 && rb1_debounce == 5 && rb2_debounce == 5) {
        modo_actual = MODO_MANUAL;
        LCD_Clear();
    }

    // UP button (RB1)
    if (rb1 && !rb1_was && rb1_debounce == 5) {
        if (modo_actual == MODO_MANUAL) {
            fan_on = 1;
            FAN_PIN = 1;
        } else if (modo_actual == MODO_CONFIG) {
            if (campo_edit == EDIT_VON) {
                int8_t next = t_von + 1;
                if (next <= T_CONFIG_MAX && (next - t_voff) >= DIFF_MIN) {
                    t_von = next;
            advertencia_activa = 0;
                } else {
                    advertencia_activa = 1;
                    advertencia_count = 0;
        }
            } else if (campo_edit == EDIT_VOFF) {
                int8_t next = t_voff + 1;
                if (next <= T_CONFIG_MAX && (t_von - next) >= DIFF_MIN) {
                    t_voff = next;
                    advertencia_activa = 0;
                } else {
                    advertencia_activa = 1;
                    advertencia_count = 0;
    }
}
        }
    }

    // DOWN button (RB2)
    if (rb2 && !rb2_was && rb2_debounce == 5) {
        if (modo_actual == MODO_MANUAL) {
            fan_on = 0;
            FAN_PIN = 0;
        } else if (modo_actual == MODO_CONFIG) {
            if (campo_edit == EDIT_VON) {
                int8_t next = t_von - 1;
                if (next >= T_CONFIG_MIN && (next - t_voff) >= DIFF_MIN) {
                    t_von = next;
                    advertencia_activa = 0;
                } else {
                    advertencia_activa = 1;
                    advertencia_count = 0;
                }
            } else if (campo_edit == EDIT_VOFF) {
                int8_t next = t_voff - 1;
                if (next >= T_CONFIG_MIN && (t_von - next) >= DIFF_MIN) {
                    t_voff = next;
                    advertencia_activa = 0;
                } else {
                    advertencia_activa = 1;
                    advertencia_count = 0;
                }
            }
        }
    }

    // Warning timer
    if (advertencia_activa) {
        advertencia_count++;
        if (advertencia_count >= 2000) {
            advertencia_activa = 0;
            advertencia_count = 0;
        }
    }
}
