// Code generated by MCHP Chatbot
#include "display.h"
#include "config.h"
#include "I2C_LCD.h"
#include <stdio.h>
#include <xc.h>

void actualizar_LCD(void) {
    char buf1[17], buf2[17];

    if (alarma_activa) {
        if (alarma_parpadeo) {
            LCD_Set_Cursor(1,1);
            LCD_Write_String("  ALERTA TEMP!  ");
            LCD_Set_Cursor(2,1);
            LCD_Write_String("   !! CRITICO!! ");
        } else {
            LCD_Clear();
        }
        return;
    }

    if (modo_actual == MODO_CONFIG) {
        if (advertencia_activa) {
            LCD_Set_Cursor(1,1);
            LCD_Write_String("  VALOR INVALIDO");
            LCD_Set_Cursor(2,1);
            LCD_Write_String("Von-Voff >= 5C! ");
            return;
        }
        if (campo_edit == EDIT_VON)
            snprintf(buf1, sizeof(buf1), "*Von:%2d  Voff:%2d", t_von, t_voff);
        else
            snprintf(buf1, sizeof(buf1), " Von:%2d *Voff:%2d", t_von, t_voff);
        LCD_Set_Cursor(1,1); LCD_Write_String(buf1);
        LCD_Set_Cursor(2,1); LCD_Write_String("UP/DN ajusta    ");
        return;
    }

    if (modo_actual == MODO_MANUAL) {
        snprintf(buf1, sizeof(buf1), "T:%.1fC  MANUAL  ", temperatura_actual);
        LCD_Set_Cursor(1,1); LCD_Write_String(buf1);
        if (fan_on)
            snprintf(buf2, sizeof(buf2), "FAN:ON  U=ON D=OF");
        else
            snprintf(buf2, sizeof(buf2), "FAN:OFF U=ON D=OF");
        LCD_Set_Cursor(2,1); LCD_Write_String(buf2);
        return;
    }

    if (modo_actual == MODO_AUTO) {
        if (vista_actual == VISTA_NORMAL) {
            snprintf(buf1, sizeof(buf1), "V:%.3fV T:%.1fC", voltaje_actual, temperatura_actual);
            LCD_Set_Cursor(1,1); LCD_Write_String(buf1);
            if (fan_on)
                LCD_Set_Cursor(2,1), LCD_Write_String("FAN:ON  AUTO    ");
            else
                LCD_Set_Cursor(2,1), LCD_Write_String("FAN:OFF AUTO    ");
        } else if (vista_actual == VISTA_MAX) {
            LCD_Set_Cursor(1,1); LCD_Write_String("  Temp. MAXIMA  ");
            snprintf(buf2, sizeof(buf2), "    %4.1f C      ", temp_max);
            LCD_Set_Cursor(2,1); LCD_Write_String(buf2);
        } else if (vista_actual == VISTA_MIN) {
            LCD_Set_Cursor(1,1); LCD_Write_String("  Temp. MINIMA  ");
            snprintf(buf2, sizeof(buf2), "    %4.1f C      ", temp_min);
            LCD_Set_Cursor(2,1); LCD_Write_String(buf2);
        }
        return;
    }
}

void animacion_inicio(void) {
    LCD_Clear();
    LCD_Set_Cursor(1, 1); LCD_Write_String("  PT100 Sistema ");
    LCD_Set_Cursor(2, 1);
    for (uint8_t i = 0; i < 16; i++) {
        LCD_Set_Cursor(2, i + 1);
        LCD_Write_Char('#');
        __delay_ms(100);
    }
    __delay_ms(500);
    LCD_Clear();
}